variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERM: linux
  GIT_STRATEGY: fetch

stages:
  - build
  - deploy

pdf:
  stage: build
  script:
    - make all
  tags:
    - generic
  artifacts:
    paths:
      - cours/prologue.pdf
      - cours/chapitre-2.pdf
      - cours/chapitre-3.pdf
      - cours/chapitre-4.pdf
      - exam/2014-a/economic-calculus-correction.pdf
      - exam/2014-a/economic-calculus.pdf
      - exam/2014-b/economic-calculus.pdf
      - exam/2015-a/economic-calculus-correction.pdf
      - exam/2015-a/economic-calculus.pdf
      - exam/2015-b/economic-calculus.pdf
      - exam/2016-a/economic-calculus-correction.pdf
      - exam/2016-a/economic-calculus.pdf
      - exam/2016-b/economic-calculus.pdf
      - exam/2017-a/economic-calculus-correction.pdf
      - exam/2017-a/economic-calculus.pdf
      - exam/2017-b/economic-calculus.pdf
      - exam/2018-a/economic-calculus-correction.pdf
      - exam/2018-a/economic-calculus.pdf
      - exam/2018-b/economic-calculus.pdf
      - td/1/td.pdf
      - td/1/correction.pdf
      - td/1/Exo-12-td-1.pdf
      - td/2/td.pdf
      - td/3/td.pdf
      - td/4/td.pdf
      - td/4/correction.pdf
      - td/fk/ctd-2.pdf
      - td/fk/ctd-3.pdf
      - td/fk/ctd-4.pdf
    expire_in: 1 day

web:
  stage: deploy
  only:
    - master@stepan/economic-calculus
  tags:
    - restricted
  dependencies:
    - pdf
  script:
    - cp cours/prologue.pdf /home/www/le-mans.adjemian.eu/calcul-économique/cours
    - cp cours/chapitre-2.pdf /home/www/le-mans.adjemian.eu/calcul-économique/cours
    - cp cours/chapitre-3.pdf /home/www/le-mans.adjemian.eu/calcul-économique/cours
    - cp cours/chapitre-4.pdf /home/www/le-mans.adjemian.eu/calcul-économique/cours
    - cp exam/2014-a/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2014-a
    - cp exam/2014-b/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2014-b
    - cp exam/2015-a/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2015-a
    - cp exam/2015-b/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2015-b
    - cp exam/2016-a/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2016-a
    - cp exam/2016-b/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2016-b
    - cp exam/2017-a/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2017-a
    - cp exam/2017-b/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2017-b
    - cp exam/2018-a/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2018-a
    - cp exam/2018-b/*.pdf /home/www/le-mans.adjemian.eu/calcul-économique/exam/2018-b
    - cp -r td/1/Exo-12-td-1.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/1/Exo-12-td-1.pdf
    - cp -r td/1/td.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/1/td.pdf
    - cp -r td/1/correction.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/1/correction.pdf
    - cp -r td/2/td.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/2/td.pdf
    - cp -r td/fk/ctd-2.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/2/ctd-2.pdf
    - cp -r td/3/td.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/3/td.pdf
    - cp -r td/fk/ctd-3.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/3/ctd-3.pdf
    - cp -r td/4/td.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/4/td.pdf
    - cp -r td/fk/ctd-4.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/4/ctd-4.pdf
    - cp -r td/4/correction.pdf /home/www/le-mans.adjemian.eu/calcul-économique/td/4/correction.pdf
