ROOT_PATH = .

all: 2014-a 2014-b 2015-a 2015-b 2016-a 2016-b 2017-a 2017-b 2018-a 2018-b 2021-a 2022-a 2022-b 2023-a 2023-b 2024-a

2014-a:
	$(MAKE) -C $(ROOT_PATH)/2014-a all

2014-b:
	$(MAKE) -C $(ROOT_PATH)/2014-b all

2015-a:
	$(MAKE) -C $(ROOT_PATH)/2015-a all

2015-b:
	$(MAKE) -C $(ROOT_PATH)/2015-b all

2016-a:
	$(MAKE) -C $(ROOT_PATH)/2016-a all

2016-b:
	$(MAKE) -C $(ROOT_PATH)/2016-b all

2017-a:
	$(MAKE) -C $(ROOT_PATH)/2017-a all

2017-b:
	$(MAKE) -C $(ROOT_PATH)/2017-b all

2018-a:
	$(MAKE) -C $(ROOT_PATH)/2018-a all

2018-b:
	$(MAKE) -C $(ROOT_PATH)/2018-b all

2021-a:
	$(MAKE) -C $(ROOT_PATH)/2021-a all

2022-a:
	$(MAKE) -C $(ROOT_PATH)/2022-a all

2022-b:
	$(MAKE) -C $(ROOT_PATH)/2022-b all

2023-a:
	$(MAKE) -C $(ROOT_PATH)/2023-a all

2023-b:
	$(MAKE) -C $(ROOT_PATH)/2023-b all

2024-a:
	$(MAKE) -C $(ROOT_PATH)/2024-a all

clean-all:
	$(MAKE) -C $(ROOT_PATH)/2014-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2014-b clean-all
	$(MAKE) -C $(ROOT_PATH)/2015-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2015-b clean-all
	$(MAKE) -C $(ROOT_PATH)/2016-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2016-b clean-all
	$(MAKE) -C $(ROOT_PATH)/2017-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2017-b clean-all
	$(MAKE) -C $(ROOT_PATH)/2018-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2018-b clean-all
	$(MAKE) -C $(ROOT_PATH)/2021-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2022-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2022-b clean-all
	$(MAKE) -C $(ROOT_PATH)/2023-a clean-all
	$(MAKE) -C $(ROOT_PATH)/2023-b clean-all
	$(MAKE) -C $(ROOT_PATH)/2024-a clean-all

.PHONY: 2014-a 2014-b 2015-a 2015-b 2016-a 2016-b 2017-a 2017-b 2018-a 2018-b 2021-a 2022-a 2022-b 2023-a 2023-b 2024-a clean-all
