ROOT_PATH = .

all: 2014-a-build 2014-b-build 2015-a-build 2015-b-build 2016-a-build 2016-b-build 2017-a-build 2017-b-build 2018-a-build

2014-a-build:
	$(MAKE) -C $(ROOT_PATH)/2014-a all

2014-a-clean:
	$(MAKE) -C $(ROOT_PATH)/2014-a clean-all

2014-b-build:
	$(MAKE) -C $(ROOT_PATH)/2014-b all

2014-b-clean:
	$(MAKE) -C $(ROOT_PATH)/2014-b clean-all

2015-a-build:
	$(MAKE) -C $(ROOT_PATH)/2015-a all

2015-a-clean:
	$(MAKE) -C $(ROOT_PATH)/2015-a clean-all

2015-b-build:
	$(MAKE) -C $(ROOT_PATH)/2015-b all

2015-b-clean:
	$(MAKE) -C $(ROOT_PATH)/2015-b clean-all

2016-a-build:
	$(MAKE) -C $(ROOT_PATH)/2016-a all

2016-a-clean:
	$(MAKE) -C $(ROOT_PATH)/2016-a clean-all

2016-b-build:
	$(MAKE) -C $(ROOT_PATH)/2016-b all

2016-b-clean:
	$(MAKE) -C $(ROOT_PATH)/2016-b clean-all

2017-a-build:
	$(MAKE) -C $(ROOT_PATH)/2017-a all

2017-a-clean:
	$(MAKE) -C $(ROOT_PATH)/2017-a clean-all

2017-b-build:
	$(MAKE) -C $(ROOT_PATH)/2017-b all

2017-b-clean:
	$(MAKE) -C $(ROOT_PATH)/2017-b clean-all

2018-a-build:
	$(MAKE) -C $(ROOT_PATH)/2018-a all

2018-a-clean:
	$(MAKE) -C $(ROOT_PATH)/2018-a clean-all

clean-all: 2014-a-clean 2015-a-clean 2016-a-clean 2017-a-clean 2017-b-clean 2014-b-clean 2015-b-clean 2016-b-clean 2018-a-clean
